config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  resources :posts, only: :index
  namespace :backend do
    resources :posts
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount TaiwanCity::Engine => '/taiwan_city'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  # validation
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/backend/posts_controller.rb
class Backend::PostsController < ApplicationController
  layout "backend"
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to [:backend, @post], notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to [:backend, @post], notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to backend_posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :city, :district, :adress, :phone, :service_time, :tag, :description, :url)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    if params[:city].present?
      @posts = Post.where(city: params[:city])
    else
      @posts = Post.all
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/backend/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">Copyright ©2017 Bater</p>
</footer>

app/views/backend/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Stand By U</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li> <%= link_to("登入", '#') %> </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/backend/posts/_form.html.erb
<%= form_for([:backend, post]) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="city-group">
    <%= select_tag(:city, options_for_select( TaiwanCity.list), class: "city-select", name: "post[city]") %>
    <%= select_tag(:district, nil ,class: "city-select", name: "post[district]") %>
  </div>


  <div class="field">
    <%= f.label :adress %>
    <%= f.text_field :adress %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :service_time %>
    <%= f.text_field :service_time %>
  </div>

  <div class="field">
    <%= f.label :tag %>
    <%= f.text_field :tag %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/backend/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', [:backend, @post] %> |
<%= link_to 'Back', backend_posts_path %>

app/views/backend/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>資源管理</h1>
<%= link_to 'New Post', new_backend_post_path, class: "btn btn-success" %>
<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>City</th>
      <th>District</th>
      <th>Adress</th>
      <th>Phone</th>
      <th>Service time</th>
      <th>Tag</th>
      <th>Description</th>
      <th>Url</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, [:backend, post] %></td>
        <td><%= TaiwanCity.get(post.city)  %></td>
        <td><%= TaiwanCity.get(post.district)  %></td>
        <td><%= post.adress %></td>
        <td><%= post.phone %></td>
        <td><%= post.service_time %></td>
        <td><%= post.tag %></td>
        <td><%= post.description %></td>
        <td><%= post.url %></td>
        <td><%= link_to 'Edit', edit_backend_post_path(post) %></td>
        <td><%= link_to 'Destroy', [:backend, post], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/backend/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', backend_posts_path %>

app/views/backend/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>City:</strong>
  <%= @post.city %>
</p>

<p>
  <strong>District:</strong>
  <%= @post.district %>
</p>

<p>
  <strong>Adress:</strong>
  <%= @post.adress %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @post.phone %>
</p>

<p>
  <strong>Service time:</strong>
  <%= @post.service_time %>
</p>

<p>
  <strong>Tag:</strong>
  <%= @post.tag %>
</p>

<p>
  <strong>Description:</strong>
  <%= @post.description %>
</p>

<p>
  <strong>Url:</strong>
  <%= @post.url %>
</p>

<%= link_to 'Edit', edit_backend_post_path(@post) %> |
<%= link_to 'Back', backend_posts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Standbyu</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/backend.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StandbyU Backend</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid">
      <%= render "backend/common/navbar" %>
      <%= yield %>
    </div>
    <%= render "backend/common/footer" %>
  </body>
</html>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="assets/SumoLanding/img/favicon.ico">

    <title>Stand By U</title>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="assets/js/ie10-viewport-bug-workaround.js"></script>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div id="h">
      <div class="logo">Stand By U</div>
      <div class="social hidden-xs">
        <a href="https://www.facebook.com/HomelessSupport"><i class="ion-social-facebook"></i></a>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-md-offset-2 centered">
            <h1>選擇你所在的縣市<br/>我們將會列出附近的資源</h1>
            <div class="mtb">
              <%= form_tag('/', method: :get) do %>
                <div class="city-group">
                  <%= select_tag(:city, options_for_select( TaiwanCity.list), class: "subscribe-input main_select city-select", name: "city") %>
                  <!--<select name="district" id="district" class="subscribe-input main_select city-select">
                    <option value="">請選擇</option>
                  </select>-->
                </div>
                <button class='btn btn-conf btn-green' type="submit">開始搜尋</button>
              <% end %>
            </div><!--/mt-->
            <h6>別擔心，這完全免費！</h6>
          </div>
        </div><!--/row-->
      </div><!--/container-->
    </div><!-- /H -->

    <!--
    <div class="container ptb">
      <div class="row">
        <div class="col-md-6">
          <h2>All the features you want in this kind of apps you'll got it here.</h2>
          <p class="mt">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>
          <p class="store">
            <a href="#"><img src="assets/img/app-store.png" height="50" alt=""></a>
            <a href="#"><img src="assets/img/google-play.png" height="50" alt=""></a>
          </p>
        </div>
        <div class="col-md-6">
          <img src="assets/img/phone.png" class="img-responsive mt" alt="">
        </div>
      </div>
    </div>

    <div id="sep">
      <div class="container">
        <div class="row centered">
          <div class="col-md-8 col-md-offset-2">
            <h1>Join your experiences with the people you care more. Let us help you.</h1>
            <h4>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.</h4>
            <p><button class="btn btn-conf-2 btn-green">Learn More</button></p>
          </div>
        </div>
      </div>
    </div>
    -->

    <div class="container ptb">
      <div class="row centered">
        <h2 class="mb">我們找到的資源如下:</h2>
        <% @posts.each do |post| %>
          <div class="col-md-4">
            <div class="price-table">
                <div class="p-head">
                  <%= post.title %>
                </div>
                <div class="p-body">
                  <ul class="features">
                    <%= content_tag :li, post.phone if post.phone.present? %>
                    <%= content_tag :li, post.adress if post.adress.present? %>｀
                    <%= content_tag :li, post.service_time if post.service_time.present? %>
                    <%= content_tag :li, post.description if post.description.present? %>
                  </ul>
                  <%= link_to '前往連結', post.url, class: "btn btn-conf-2 btn-green" %>
                </div><!--/p-body-->
            </div><!--/price-table-->
          </div><!--/col-md-4-->
        <% end %>
        <%= "很抱歉！你所在的區域目前沒有資料。" if @posts.blank? %>
      </div><!--/row-->
    </div><!--/container-->

    <!-- logo block
    <div id="g">
      <div class="container">
        <div class="row sponsor centered">
          <div class="col-sm-2 col-sm-offset-1">
            <img src="assets/img/client1.png" alt="">
          </div>
          <div class="col-sm-2">
            <img src="assets/img/client3.png" alt="">
          </div>
          <div class="col-sm-2">
            <img src="assets/img/client2.png" alt="">
          </div>
          <div class="col-sm-2">
            <img src="assets/img/client4.png" alt="">
          </div>
          <div class="col-sm-2">
            <img src="assets/img/client5.png" alt="">
          </div>
        </div>
      </div>
    </div>

    <div id="green">
      <div class="container">
        <div class="row">
          <div class="col-md-6 col-md-offset-3 centered">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

              <div class="carousel-inner">
                <div class="item active">
                  <h3>I enjoyed so much the last edition of Landing Sumo, that I bought the tickets for the new one edition of the event the first day.</h3>
                  <h5><tgr>DAVID JHONSON</tgr></h5>
                </div>
                <div class="item">
                  <h3>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</h3>
                  <h5><tgr>MARK LAWRENCE</tgr></h5>
                </div>
                <div class="item">
                  <h3>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration, by injected humour.</h3>
                  <h5><tgr>LISA SMITH</tgr></h5>
                </div>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>-->

    <div id="f">
      <div class="container">
        <div class="row centered">
          <h6 class="mt">COPYRIGHT 2017 - Bater Chen</h6>
          <h6 class="mt">Design by LANDING SUMO</h6>
        </div><!--/row-->
      </div><!--/container-->
    </div><!--/F-->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="assets/js/retina-1.1.0.js"></script>
  </body>
</html>